export const ESSENTIAL_GROUPS = [
  {
    id: 'verbs',
    eyebrow: 'Action words',
    title: 'Most-used verbs',
    description: 'The verbs that appear constantly in beginner sentences.',
    illustration: true,
    items: [
      {
        id: 'etre',
        french: 'être',
        display: 'être',
        english: 'to be',
        example: 'Je suis ici.',
        highlight: 'suis',
        conjugation: { je: 'suis', tu: 'es', il: 'est', nous: 'sommes', vous: 'êtes', ils: 'sont' },
      },
      {
        id: 'avoir',
        french: 'avoir',
        display: 'avoir',
        english: 'to have',
        example: "J'ai un livre.",
        highlight: 'ai',
        conjugation: { je: 'ai', tu: 'as', il: 'a', nous: 'avons', vous: 'avez', ils: 'ont' },
      },
      {
        id: 'aller',
        french: 'aller',
        display: 'aller',
        english: 'to go',
        example: 'Je vais bien.',
        highlight: 'vais',
        conjugation: { je: 'vais', tu: 'vas', il: 'va', nous: 'allons', vous: 'allez', ils: 'vont' },
      },
      {
        id: 'faire',
        french: 'faire',
        display: 'faire',
        english: 'to do / make',
        example: 'Je fais ça.',
        highlight: 'fais',
        conjugation: { je: 'fais', tu: 'fais', il: 'fait', nous: 'faisons', vous: 'faites', ils: 'font' },
      },
      {
        id: 'dire',
        french: 'dire',
        display: 'dire',
        english: 'to say',
        example: 'Je dis bonjour.',
        highlight: 'dis',
        conjugation: { je: 'dis', tu: 'dis', il: 'dit', nous: 'disons', vous: 'dites', ils: 'disent' },
      },
      {
        id: 'pouvoir',
        french: 'pouvoir',
        display: 'pouvoir',
        english: 'can / to be able',
        example: 'Je peux aider.',
        highlight: 'peux',
        conjugation: { je: 'peux', tu: 'peux', il: 'peut', nous: 'pouvons', vous: 'pouvez', ils: 'peuvent' },
      },
      {
        id: 'vouloir',
        french: 'vouloir',
        display: 'vouloir',
        english: 'to want',
        example: 'Je veux apprendre.',
        highlight: 'veux',
        conjugation: { je: 'veux', tu: 'veux', il: 'veut', nous: 'voulons', vous: 'voulez', ils: 'veulent' },
      },
      {
        id: 'venir',
        french: 'venir',
        display: 'venir',
        english: 'to come',
        example: 'Je viens demain.',
        highlight: 'viens',
        conjugation: { je: 'viens', tu: 'viens', il: 'vient', nous: 'venons', vous: 'venez', ils: 'viennent' },
      },
      {
        id: 'prendre',
        french: 'prendre',
        display: 'prendre',
        english: 'to take',
        example: 'Je prends le train.',
        highlight: 'prends',
        conjugation: { je: 'prends', tu: 'prends', il: 'prend', nous: 'prenons', vous: 'prenez', ils: 'prennent' },
      },
      {
        id: 'voir',
        french: 'voir',
        display: 'voir',
        english: 'to see',
        example: 'Je vois la maison.',
        highlight: 'vois',
        conjugation: { je: 'vois', tu: 'vois', il: 'voit', nous: 'voyons', vous: 'voyez', ils: 'voient' },
      },
      {
        id: 'savoir',
        french: 'savoir',
        display: 'savoir',
        english: 'to know',
        example: 'Je sais la réponse.',
        highlight: 'sais',
        conjugation: { je: 'sais', tu: 'sais', il: 'sait', nous: 'savons', vous: 'savez', ils: 'savent' },
      },
      {
        id: 'devoir',
        french: 'devoir',
        display: 'devoir',
        english: 'must / to have to',
        example: 'Je dois partir.',
        highlight: 'dois',
        conjugation: { je: 'dois', tu: 'dois', il: 'doit', nous: 'devons', vous: 'devez', ils: 'doivent' },
      },
      {
        id: 'mettre',
        french: 'mettre',
        display: 'mettre',
        english: 'to put',
        example: 'Je mets la table.',
        highlight: 'mets',
        conjugation: { je: 'mets', tu: 'mets', il: 'met', nous: 'mettons', vous: 'mettez', ils: 'mettent' },
      },
      {
        id: 'croire',
        french: 'croire',
        display: 'croire',
        english: 'to believe',
        example: 'Je crois Paul.',
        highlight: 'crois',
        conjugation: { je: 'crois', tu: 'crois', il: 'croit', nous: 'croyons', vous: 'croyez', ils: 'croient' },
      },
      {
        id: 'trouver',
        french: 'trouver',
        display: 'trouver',
        english: 'to find',
        example: 'Je trouve la clé.',
        highlight: 'trouve',
        conjugation: { je: 'trouve', tu: 'trouves', il: 'trouve', nous: 'trouvons', vous: 'trouvez', ils: 'trouvent' },
      },
      {
        id: 'donner',
        french: 'donner',
        display: 'donner',
        english: 'to give',
        example: 'Je donne un livre.',
        highlight: 'donne',
        conjugation: { je: 'donne', tu: 'donnes', il: 'donne', nous: 'donnons', vous: 'donnez', ils: 'donnent' },
      },
      {
        id: 'parler',
        french: 'parler',
        display: 'parler',
        english: 'to speak',
        example: 'Je parle français.',
        highlight: 'parle',
        conjugation: { je: 'parle', tu: 'parles', il: 'parle', nous: 'parlons', vous: 'parlez', ils: 'parlent' },
      },
      {
        id: 'aimer',
        french: 'aimer',
        display: 'aimer',
        english: 'to like / love',
        example: "J'aime ce mot.",
        highlight: 'aime',
        conjugation: { je: 'aime', tu: 'aimes', il: 'aime', nous: 'aimons', vous: 'aimez', ils: 'aiment' },
      },
      {
        id: 'passer',
        french: 'passer',
        display: 'passer',
        english: 'to pass / spend time',
        example: 'Je passe devant toi.',
        highlight: 'passe',
        conjugation: { je: 'passe', tu: 'passes', il: 'passe', nous: 'passons', vous: 'passez', ils: 'passent' },
      },
      {
        id: 'penser',
        french: 'penser',
        display: 'penser',
        english: 'to think',
        example: 'Je pense à toi.',
        highlight: 'pense',
        conjugation: { je: 'pense', tu: 'penses', il: 'pense', nous: 'pensons', vous: 'pensez', ils: 'pensent' },
      },
      {
        id: 'rester',
        french: 'rester',
        display: 'rester',
        english: 'to stay',
        example: 'Je reste ici.',
        highlight: 'reste',
        conjugation: { je: 'reste', tu: 'restes', il: 'reste', nous: 'restons', vous: 'restez', ils: 'restent' },
      },
      {
        id: 'arriver',
        french: 'arriver',
        display: 'arriver',
        english: 'to arrive / happen',
        example: "J'arrive demain.",
        highlight: 'arrive',
        conjugation: { je: 'arrive', tu: 'arrives', il: 'arrive', nous: 'arrivons', vous: 'arrivez', ils: 'arrivent' },
      },
      {
        id: 'connaitre',
        french: 'connaître',
        display: 'connaître',
        english: 'to know / be familiar with',
        example: 'Je connais Paris.',
        highlight: 'connais',
        conjugation: { je: 'connais', tu: 'connais', il: 'connaît', nous: 'connaissons', vous: 'connaissez', ils: 'connaissent' },
      },
      {
        id: 'demander',
        french: 'demander',
        display: 'demander',
        english: 'to ask',
        example: 'Je demande le prix.',
        highlight: 'demande',
        conjugation: { je: 'demande', tu: 'demandes', il: 'demande', nous: 'demandons', vous: 'demandez', ils: 'demandent' },
      },
      {
        id: 'tenir',
        french: 'tenir',
        display: 'tenir',
        english: 'to hold',
        example: 'Je tiens la porte.',
        highlight: 'tiens',
        conjugation: { je: 'tiens', tu: 'tiens', il: 'tient', nous: 'tenons', vous: 'tenez', ils: 'tiennent' },
      },
      {
        id: 'sembler',
        french: 'sembler',
        display: 'sembler',
        english: 'to seem',
        example: 'Ça semble facile.',
        highlight: 'semble',
        conjugation: { je: 'semble', tu: 'sembles', il: 'semble', nous: 'semblons', vous: 'semblez', ils: 'semblent' },
      },
      {
        id: 'laisser',
        french: 'laisser',
        display: 'laisser',
        english: 'to leave / let',
        example: 'Je laisse la clé.',
        highlight: 'laisse',
        conjugation: { je: 'laisse', tu: 'laisses', il: 'laisse', nous: 'laissons', vous: 'laissez', ils: 'laissent' },
      },
      {
        id: 'comprendre',
        french: 'comprendre',
        display: 'comprendre',
        english: 'to understand',
        example: 'Je comprends la phrase.',
        highlight: 'comprends',
        conjugation: { je: 'comprends', tu: 'comprends', il: 'comprend', nous: 'comprenons', vous: 'comprenez', ils: 'comprennent' },
      },
      {
        id: 'sortir',
        french: 'sortir',
        display: 'sortir',
        english: 'to go out',
        example: 'Je sors ce soir.',
        highlight: 'sors',
        conjugation: { je: 'sors', tu: 'sors', il: 'sort', nous: 'sortons', vous: 'sortez', ils: 'sortent' },
      },
      {
        id: 'vivre',
        french: 'vivre',
        display: 'vivre',
        english: 'to live',
        example: 'Je vis à Lyon.',
        highlight: 'vis',
        conjugation: { je: 'vis', tu: 'vis', il: 'vit', nous: 'vivons', vous: 'vivez', ils: 'vivent' },
      },
      {
        id: 'rendre',
        french: 'rendre',
        display: 'rendre',
        english: 'to return / give back',
        example: 'Je rends le stylo.',
        highlight: 'rends',
        conjugation: { je: 'rends', tu: 'rends', il: 'rend', nous: 'rendons', vous: 'rendez', ils: 'rendent' },
      },
      {
        id: 'attendre',
        french: 'attendre',
        display: 'attendre',
        english: 'to wait for',
        example: "J'attends le bus.",
        highlight: 'attends',
        conjugation: { je: 'attends', tu: 'attends', il: 'attend', nous: 'attendons', vous: 'attendez', ils: 'attendent' },
      },
      {
        id: 'partir',
        french: 'partir',
        display: 'partir',
        english: 'to leave',
        example: 'Je pars maintenant.',
        highlight: 'pars',
        conjugation: { je: 'pars', tu: 'pars', il: 'part', nous: 'partons', vous: 'partez', ils: 'partent' },
      },
      {
        id: 'porter',
        french: 'porter',
        display: 'porter',
        english: 'to wear / carry',
        example: 'Je porte un sac.',
        highlight: 'porte',
        conjugation: { je: 'porte', tu: 'portes', il: 'porte', nous: 'portons', vous: 'portez', ils: 'portent' },
      },
      {
        id: 'entrer',
        french: 'entrer',
        display: 'entrer',
        english: 'to enter',
        example: "J'entre dans la salle.",
        highlight: 'entre',
        conjugation: { je: 'entre', tu: 'entres', il: 'entre', nous: 'entrons', vous: 'entrez', ils: 'entrent' },
      },
      {
        id: 'appeler',
        french: 'appeler',
        display: 'appeler',
        english: 'to call',
        example: "J'appelle Marie.",
        highlight: 'appelle',
        conjugation: { je: 'appelle', tu: 'appelles', il: 'appelle', nous: 'appelons', vous: 'appelez', ils: 'appellent' },
      },
      {
        id: 'tomber',
        french: 'tomber',
        display: 'tomber',
        english: 'to fall',
        example: 'La pluie tombe.',
        highlight: 'tombe',
        conjugation: { je: 'tombe', tu: 'tombes', il: 'tombe', nous: 'tombons', vous: 'tombez', ils: 'tombent' },
      },
      {
        id: 'commencer',
        french: 'commencer',
        display: 'commencer',
        english: 'to begin',
        example: 'Je commence demain.',
        highlight: 'commence',
        conjugation: { je: 'commence', tu: 'commences', il: 'commence', nous: 'commençons', vous: 'commencez', ils: 'commencent' },
      },
      {
        id: 'suivre',
        french: 'suivre',
        display: 'suivre',
        english: 'to follow',
        example: 'Je suis le guide.',
        highlight: 'suis',
        conjugation: { je: 'suis', tu: 'suis', il: 'suit', nous: 'suivons', vous: 'suivez', ils: 'suivent' },
      },
      {
        id: 'ecouter',
        french: 'écouter',
        display: 'écouter',
        english: 'to listen',
        example: "J'écoute la question.",
        highlight: 'écoute',
        conjugation: { je: 'écoute', tu: 'écoutes', il: 'écoute', nous: 'écoutons', vous: 'écoutez', ils: 'écoutent' },
      },
      {
        id: 'regarder',
        french: 'regarder',
        display: 'regarder',
        english: 'to watch / look at',
        example: 'Je regarde la carte.',
        highlight: 'regarde',
        conjugation: { je: 'regarde', tu: 'regardes', il: 'regarde', nous: 'regardons', vous: 'regardez', ils: 'regardent' },
      },
      {
        id: 'travailler',
        french: 'travailler',
        display: 'travailler',
        english: 'to work',
        example: 'Je travaille ici.',
        highlight: 'travaille',
        conjugation: { je: 'travaille', tu: 'travailles', il: 'travaille', nous: 'travaillons', vous: 'travaillez', ils: 'travaillent' },
      },
      {
        id: 'manger',
        french: 'manger',
        display: 'manger',
        english: 'to eat',
        example: 'Je mange une pomme.',
        highlight: 'mange',
        conjugation: { je: 'mange', tu: 'manges', il: 'mange', nous: 'mangeons', vous: 'mangez', ils: 'mangent' },
      },
      {
        id: 'jouer',
        french: 'jouer',
        display: 'jouer',
        english: 'to play',
        example: 'Je joue avec toi.',
        highlight: 'joue',
        conjugation: { je: 'joue', tu: 'joues', il: 'joue', nous: 'jouons', vous: 'jouez', ils: 'jouent' },
      },
      {
        id: 'lire',
        french: 'lire',
        display: 'lire',
        english: 'to read',
        example: 'Je lis le message.',
        highlight: 'lis',
        conjugation: { je: 'lis', tu: 'lis', il: 'lit', nous: 'lisons', vous: 'lisez', ils: 'lisent' },
      },
      {
        id: 'ecrire',
        french: 'écrire',
        display: 'écrire',
        english: 'to write',
        example: "J'écris un mot.",
        highlight: 'écris',
        conjugation: { je: 'écris', tu: 'écris', il: 'écrit', nous: 'écrivons', vous: 'écrivez', ils: 'écrivent' },
      },
      {
        id: 'ouvrir',
        french: 'ouvrir',
        display: 'ouvrir',
        english: 'to open',
        example: "J'ouvre la porte.",
        highlight: 'ouvre',
        conjugation: { je: 'ouvre', tu: 'ouvres', il: 'ouvre', nous: 'ouvrons', vous: 'ouvrez', ils: 'ouvrent' },
      },
      {
        id: 'repondre',
        french: 'répondre',
        display: 'répondre',
        english: 'to answer',
        example: 'Je réponds vite.',
        highlight: 'réponds',
        conjugation: { je: 'réponds', tu: 'réponds', il: 'répond', nous: 'répondons', vous: 'répondez', ils: 'répondent' },
      },
      {
        id: 'perdre',
        french: 'perdre',
        display: 'perdre',
        english: 'to lose',
        example: 'Je perds mes clés.',
        highlight: 'perds',
        conjugation: { je: 'perds', tu: 'perds', il: 'perd', nous: 'perdons', vous: 'perdez', ils: 'perdent' },
      },
      {
        id: 'payer',
        french: 'payer',
        display: 'payer',
        english: 'to pay',
        example: 'Je paie le café.',
        highlight: 'paie',
        conjugation: { je: 'paie', tu: 'paies', il: 'paie', nous: 'payons', vous: 'payez', ils: 'paient' },
      },
    ],
  },
  {
    id: 'prepositions',
    eyebrow: 'Linking words',
    title: 'Core prepositions',
    description: 'Small words that connect people, places, and objects.',
    illustration: true,
    items: [
      { id: 'a', french: 'à', display: 'à', english: 'to / at / in', example: 'Je vais à Paris.', highlight: 'à' },
      { id: 'de', french: 'de', display: 'de', english: 'of / from', example: 'Je viens de Lyon.', highlight: 'de' },
      { id: 'dans', french: 'dans', display: 'dans', english: 'in / inside', example: 'Dans la boite.', highlight: 'Dans' },
      { id: 'sur', french: 'sur', display: 'sur', english: 'on', example: 'Sur la table.', highlight: 'Sur' },
      { id: 'avec', french: 'avec', display: 'avec', english: 'with', example: 'Avec mon ami.', highlight: 'Avec' },
      { id: 'pour', french: 'pour', display: 'pour', english: 'for', example: 'Pour toi.', highlight: 'Pour' },
      { id: 'chez', french: 'chez', display: 'chez', english: 'at the home of', example: 'Chez Marie.', highlight: 'Chez' },
      { id: 'sans', french: 'sans', display: 'sans', english: 'without', example: 'Sans sucre.', highlight: 'Sans' },
      { id: 'avant', french: 'avant', display: 'avant', english: 'before', example: 'Je pars avant midi.', highlight: 'avant' },
      { id: 'apres', french: 'après', display: 'après', english: 'after', example: 'Je viens après toi.', highlight: 'après' },
      { id: 'pendant', french: 'pendant', display: 'pendant', english: 'during / for', example: "J'écoute pendant le cours.", highlight: 'pendant' },
      { id: 'entre', french: 'entre', display: 'entre', english: 'between', example: 'Le café est entre deux rues.', highlight: 'entre' },
      { id: 'contre', french: 'contre', display: 'contre', english: 'against', example: 'Le vélo est contre le mur.', highlight: 'contre' },
      { id: 'devant', french: 'devant', display: 'devant', english: 'in front of', example: 'Je suis devant la gare.', highlight: 'devant' },
      { id: 'derriere', french: 'derrière', display: 'derrière', english: 'behind', example: 'Le jardin est derrière la maison.', highlight: 'derrière' },
      { id: 'sous', french: 'sous', display: 'sous', english: 'under', example: 'Le sac est sous la table.', highlight: 'sous' },
      { id: 'vers', french: 'vers', display: 'vers', english: 'toward / around', example: 'Je marche vers le parc.', highlight: 'vers' },
      { id: 'depuis', french: 'depuis', display: 'depuis', english: 'since / from', example: 'Je travaille depuis lundi.', highlight: 'depuis' },
      { id: 'selon', french: 'selon', display: 'selon', english: 'according to', example: 'Selon Marie, tout va bien.', highlight: 'Selon' },
      { id: 'parmi', french: 'parmi', display: 'parmi', english: 'among', example: 'Il est parmi les amis.', highlight: 'parmi' },
    ],
  },
  {
    id: 'colors',
    eyebrow: 'Descriptions',
    title: 'Useful colors',
    description: 'Common color words for describing everyday things.',
    illustration: true,
    items: [
      { id: 'rouge', french: 'rouge', display: 'rouge', english: 'red', example: 'La pomme est rouge.', color: '#f04d3a' },
      { id: 'bleu', french: 'bleu', display: 'bleu', english: 'blue', example: 'Le ciel est bleu.', color: '#284bff' },
      { id: 'vert', french: 'vert', display: 'vert', english: 'green', example: 'Le parc est vert.', color: '#227a4d' },
      { id: 'jaune', french: 'jaune', display: 'jaune', english: 'yellow', example: 'Le citron est jaune.', color: '#e7ad34' },
      { id: 'noir', french: 'noir', display: 'noir', english: 'black', example: 'Le cafe est noir.', color: '#1c1913' },
      { id: 'blanc', french: 'blanc', display: 'blanc', english: 'white', example: 'Le mur est blanc.', color: '#ffffff' },
      { id: 'gris', french: 'gris', display: 'gris', english: 'gray', example: 'Le nuage est gris.', color: '#8a8579' },
      { id: 'rose', french: 'rose', display: 'rose', english: 'pink', example: 'La fleur est rose.', color: '#f48fb1' },
      { id: 'orange', french: 'orange', display: 'orange', english: 'orange', example: 'La carotte est orange.', color: '#f97316' },
      { id: 'violet', french: 'violet', display: 'violet', english: 'purple', example: 'Le raisin est violet.', color: '#7c3aed' },
      { id: 'marron', french: 'marron', display: 'marron', english: 'brown', example: 'Le sac est marron.', color: '#7a4a24' },
      { id: 'beige', french: 'beige', display: 'beige', english: 'beige', example: 'Le manteau est beige.', color: '#d8b98f' },
      { id: 'turquoise', french: 'turquoise', display: 'turquoise', english: 'turquoise', example: 'La mer est turquoise.', color: '#2dd4bf' },
      { id: 'dore', french: 'doré', display: 'doré', english: 'gold', example: 'Le cadre est doré.', color: '#d6a21f' },
      { id: 'argente', french: 'argenté', display: 'argenté', english: 'silver', example: 'Le stylo est argenté.', color: '#b8bec8' },
      { id: 'bleu_marine', french: 'bleu marine', display: 'bleu marine', english: 'navy blue', example: 'Le pull est bleu marine.', color: '#172554' },
    ],
  },
  {
    id: 'days',
    eyebrow: 'Calendar',
    title: 'Days of the week',
    description: 'Hear, translate, and lock the Monday-to-Sunday order.',
    illustration: false,
    items: [
      { id: 'lundi', french: 'lundi', display: 'lundi', english: 'Monday', example: 'Lundi matin.' },
      { id: 'mardi', french: 'mardi', display: 'mardi', english: 'Tuesday', example: 'Mardi soir.' },
      { id: 'mercredi', french: 'mercredi', display: 'mercredi', english: 'Wednesday', example: 'Mercredi midi.' },
      { id: 'jeudi', french: 'jeudi', display: 'jeudi', english: 'Thursday', example: 'Jeudi prochain.' },
      { id: 'vendredi', french: 'vendredi', display: 'vendredi', english: 'Friday', example: 'Vendredi soir.' },
      { id: 'samedi', french: 'samedi', display: 'samedi', english: 'Saturday', example: 'Samedi matin.' },
      { id: 'dimanche', french: 'dimanche', display: 'dimanche', english: 'Sunday', example: 'Dimanche après-midi.' },
    ],
  },
  {
    id: 'months',
    eyebrow: 'Calendar',
    title: 'Months of the year',
    description: 'Practice month names, translation, and the January-to-December order.',
    illustration: false,
    items: [
      { id: 'janvier', french: 'janvier', display: 'janvier', english: 'January', example: 'En janvier.' },
      { id: 'fevrier', french: 'février', display: 'février', english: 'February', example: 'En février.' },
      { id: 'mars', french: 'mars', display: 'mars', english: 'March', example: 'En mars.' },
      { id: 'avril', french: 'avril', display: 'avril', english: 'April', example: 'En avril.' },
      { id: 'mai', french: 'mai', display: 'mai', english: 'May', example: 'En mai.' },
      { id: 'juin', french: 'juin', display: 'juin', english: 'June', example: 'En juin.' },
      { id: 'juillet', french: 'juillet', display: 'juillet', english: 'July', example: 'En juillet.' },
      { id: 'aout', french: 'août', display: 'août', english: 'August', example: 'En août.' },
      { id: 'septembre', french: 'septembre', display: 'septembre', english: 'September', example: 'En septembre.' },
      { id: 'octobre', french: 'octobre', display: 'octobre', english: 'October', example: 'En octobre.' },
      { id: 'novembre', french: 'novembre', display: 'novembre', english: 'November', example: 'En novembre.' },
      { id: 'decembre', french: 'décembre', display: 'décembre', english: 'December', example: 'En décembre.' },
    ],
  },
];

export const ESSENTIAL_ITEMS = ESSENTIAL_GROUPS.flatMap((group) =>
  group.items.map((item) => ({
    ...item,
    groupId: group.id,
  })),
);

export function buildEssentialChallengeQuestions(group) {
  if (isCalendarSequenceGroup(group)) {
    return [
      ...group.items.flatMap((item) => [
        { item, mode: 'listening' },
        { item, mode: 'dictation' },
        { item, mode: 'translate' },
      ]),
      { items: group.items, mode: 'sequence' },
    ];
  }

  return group.items.map((item, index) => ({
    item,
    mode: index % 2 === 0 ? 'meaning' : 'listening',
  }));
}

export function isCalendarSequenceGroup(group) {
  return ['days', 'months'].includes(group.id);
}

export function getEssentialAnswerKind(question) {
  if (question.mode === 'sequence') return 'sequence';
  return question.mode === 'translate' ? 'english' : 'french';
}

export function shouldAutoPlayEssentialQuestion(question) {
  return ['listening', 'dictation', 'translate'].includes(question.mode);
}

export function validateEssentialAnswer(value, item, expectedKind = 'french') {
  if (expectedKind === 'sequence') return validateEssentialSequenceAnswer(value, item);

  const actual = normalizeEssentialAnswer(value);
  if (!actual) return false;
  const acceptedAnswers =
    expectedKind === 'english'
      ? [item.english]
      : [item.french, item.display];
  return acceptedAnswers.some((accepted) => actual === normalizeEssentialAnswer(accepted));
}

export function normalizeEssentialAnswer(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z]/g, '');
}

export function validateEssentialSequenceAnswer(value, items) {
  const actual = String(value || '')
    .split(/\r?\n/)
    .map(normalizeEssentialAnswer)
    .filter(Boolean);
  const expected = items.map((item) => normalizeEssentialAnswer(item.french));

  if (actual.length !== expected.length) return false;
  return expected.every((day, index) => actual[index] === day);
}
